## Druid 数据库连接信息 START ##
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/first_vue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC"
    username: root
    password: xyy123
    driver-class-name: com.mysql.jdbc.Driver
    ################### 以下为druid增加的配置 ###########################
    type: com.alibaba.druid.pool.DruidDataSource

    # 下面为连接池的补充设置，应用到上面所有数据源中

    #------------------------------------------------------------------------------------------------------------------------------------#
    # 初始化大小
    initialSize: 100
    # 最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接,
    minIdle: 100
    # 最大活动连接:连接池在同一时间能够分配的最大活动连接的数量,
    maxActive: 3000
    # 最大等待时间:当没有可用连接时,连接池等待连接被归还的最大时间(以毫秒计数),
    maxWait: 2000
    #-----------------------------------------------------------------------------------------------------------------------------------#

    #------------------------------------------------------------------------------------------------------------------------------------#
    # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
    validationQuery: SELECT 1 FROM DUAL
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    # 注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    testWhileIdle: true
    # 指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个.
    # 注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    testOnBorrow: false
    #指明是否在归还到池中前进行检验
    #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    testOnReturn: false
    # 在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位.如果设置为非正数,则不运行空闲连接回收器线程
    timeBetweenEvictionRunsMillis: 60000
    # 在每次空闲连接回收器线程(如果有)运行时检查的连接数量
    numTestsPerEvictionRun: 20
    # 连接在池中保持空闲而不被空闲连接回收器线程,(如果有)回收的最小时间值，单位毫秒
    minEvictableIdleTimeMillis: 180000
    #------------------------------------------------------------------------------------------------------------------------------------#

    #------------------------------------------------------------------------------------------------------------------------------------#
    # 打开PSCache，并且指定每个连接上PSCache的大小,0表示不限制
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #------------------------------------------------------------------------------------------------------------------------------------#

    #------------------------------------------------------------------------------------------------------------------------------------#
    # 标记是否删除泄露的连接,如果他们超过了removeAbandonedTimout的限制.
    # 如果设置为true, 连接被认为是被泄露并且可以被删除,如果空闲时间超过removeAbandonedTimeout.
    removeAbandoned: false
    # 泄露的连接可以被删除的超时值, 单位秒
    removeAbandonedTimeout: 300
    # 标记当Statement或连接被泄露时是否打印程序的stack traces日志。 被泄露的Statements和连接的日志添加在每个连接打开或者生成新的Statement, 因为需要生成stack trace。
    logAbandoned: false
    # 如果开启"removeAbandoned",那么连接在被认为泄露时可能被池回收. 这个机制在(getNumIdle() < 2)
    # and (getNumActive() > getMaxActive() - 3)时被触发.
    # 举例当maxActive=20, 活动连接为18,空闲连接为1时可以触发"removeAbandoned".
    # 但是活动连接只有在没有被使用的时间超过"removeAbandonedTimeout"时才被删除,默认300秒.
    # 在resultset中游历不被计算为被使用.
    #------------------------------------------------------------------------------------------------------------------------------------#

    #------------------------------------------------------------------------------------------------------------------------------------#
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-FieldUtil-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #------------------------------------------------------------------------------------------------------------------------------------#

  stratview:
    urlMappings: "/druid/*"
    # IP白名单 (没有配置或者为空，则允许所有访问)
    allow: 127.0.0.1
    # IP黑名单 (存在共同时，deny优先于allow)
    deny:
    loginUsername: admin
    loginPassword: admin
    resetEnable: false
    filterUrlPatterns: "/*"
    filterExclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
## Druid 数据库连接信息 END ##

xing:
  fileUrl: "d:/gitRepository/file/"
